name: Run tests and upload coverage

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run coverage and upload to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry add  pytest-cov

      - name: Run tests and generate coverage report
        run: |
          poetry run pytest --cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
